blank_issues_enabled: false
contact_links:
  - name: ReadMe
    url: https://github.com/hass-emulated-hue/core#hue-emulation-for-home-assistant
    about: Find general information about the project and some basic support answers
  - name: Discussions
    url: https://github.com/hass-emulated-hue/core/discussions
    about: Ask questions and talk about the project casually